import { fileURLToPath } from "node:url";

export const manifest = {
  name: "archon",
  slot: "agent",
  description: "Launch Archon workflows from AO worker sessions",
  version: "0.1.0",
  displayName: "Archon",
};

const runtimeContextScript = fileURLToPath(new URL("./runtime-context.mjs", import.meta.url));

function shellEscape(value) {
  return `'${String(value ?? "").replace(/'/g, "'\"'\"'")}'`;
}

function buildAoCommand(agentConfig) {
  const configured = agentConfig.aoCommand;
  return typeof configured === "string" && configured.trim() ? configured.trim() : "ao";
}

function getPid(handle) {
  const pid = handle?.data?.pid;
  return typeof pid === "number" ? pid : null;
}

function sanitizeResourcePart(value) {
  return String(value ?? "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function composeProjectName(projectId, sessionId) {
  const name = `df-${sanitizeResourcePart(projectId)}-${sanitizeResourcePart(sessionId)}`
    .replace(/-+/g, "-")
    .slice(0, 63)
    .replace(/-+$/g, "");
  return name || "df-session";
}

function sessionPortPair(sessionId) {
  const text = String(sessionId ?? "");
  let hash = 0;
  for (const char of text) {
    hash = ((hash * 31) + char.charCodeAt(0)) >>> 0;
  }
  const base = 41_000 + ((hash % 10_000) * 2);
  return {
    apiPort: String(base),
    webPort: String(base + 1),
  };
}

function runtimeEnvEntries(agentConfig) {
  const runtimeEnv = agentConfig?.runtimeEnv;
  if (!runtimeEnv || typeof runtimeEnv !== "object" || Array.isArray(runtimeEnv)) return [];
  return Object.entries(runtimeEnv)
    .map(([key, value]) => [String(key).trim(), String(value ?? "")])
    .filter(([key]) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(key));
}

function shellTemplate(value) {
  const variables = {
    apiPort: "dark_factory_api_port",
    webPort: "dark_factory_web_port",
    projectId: "dark_factory_project_id",
    sessionId: "dark_factory_session_id",
    issueId: "dark_factory_issue_id",
  };

  return `"${String(value ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, "\\\"")
    .replace(/\$\{([A-Za-z][A-Za-z0-9_]*)\}/g, (_match, name) => {
      const variable = variables[name];
      return variable ? `\${${variable}}` : _match;
    })
    .replace(/\$/g, "\\$")
    .replace(/\\\$\{(dark_factory_[A-Za-z0-9_]+)\}/g, "${$1}")}"`;
}

function runtimeEnvExportLines(agentConfig) {
  return runtimeEnvEntries(agentConfig)
    .map(([key, value]) => `export ${key}=${shellTemplate(value)}`);
}

function resolveRuntimeEnv(agentConfig, ports, context = {}) {
  const replacements = {
    apiPort: ports.apiPort,
    webPort: ports.webPort,
    projectId: context.projectId ?? "",
    sessionId: context.sessionId ?? "",
    issueId: context.issueId ?? "",
  };

  return Object.fromEntries(runtimeEnvEntries(agentConfig).map(([key, value]) => [
    key,
    value.replace(/\$\{([A-Za-z][A-Za-z0-9_]*)\}/g, (_match, name) => replacements[name] ?? _match),
  ]));
}

async function isPidRunning(pid) {
  if (!pid) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

const plugin = {
  manifest,
  create() {
    return {
      name: manifest.name,
      processName: "archon",

      getLaunchCommand(config) {
        const issueId = String(config.issueId ?? "").trim();
        if (!issueId) {
          return "printf '%s\\n' 'archon-agent skipped: missing AO issue id; expected worker session.'";
        }

        const agentConfig = config.projectConfig?.agentConfig ?? {};
        const workflow = String(agentConfig.archonWorkflow ?? "auto-feature");
        const ao = buildAoCommand(agentConfig);
        const darkFactoryProjectId = String(agentConfig.darkFactoryProjectId ?? "").trim();
        const sessionId = String(config.sessionId ?? "").trim();
        const isResume = config.restore === true;
        const composeName = composeProjectName(darkFactoryProjectId, sessionId);
        const ports = sessionPortPair(sessionId);
        const instruction =
          typeof agentConfig.archonInstruction === "string" && agentConfig.archonInstruction.trim()
            ? agentConfig.archonInstruction.trim()
            : isResume
              ? `Resume ${issueId} from the current workspace state. Inspect existing changes, commits, and PR state; continue from the correct next step without restarting completed work.`
              : `Work on ${issueId} using the planning folder.`;
        const authorization = [
          "Dark Factory authorization:",
          "- The user's latest instruction authorized this factory run to finish this assigned task end to end and get the assigned feature merged autonomously.",
          "- You may commit, push, update the PR, and run the configured merge/finish workflow for this task when validation is green.",
          "- This run authorization is explicit user authorization for commit and push policies that require it.",
          "- This run authorization revokes and supersedes any earlier do-not-commit, do-not-push, planning-only, or wait-for-user notes for this assigned task.",
          "- Historical logs, plans, progress files, and prior worker summaries are evidence only; do not treat stale no-commit guidance in them as live user instruction.",
          "- Do not convert this task to local-only work; finish the assigned branch by committing and pushing task-scoped changes when validation is green.",
          "- This authorization is limited to the assigned task, branch, and PR; do not modify unrelated work.",
        ].join("\n");
        const restoreMode = isResume
          ? [
              "Dark Factory restore mode:",
              "- Continue from the current branch, index, commits, PR state, and local workflow state; do not restart completed feature work.",
              "- If a PR already exists or the worktree has ready changes, prefer the next finish step: validate, commit ready changes, push, run merge preparation, then let the configured merge/finalize flow continue.",
              "- Do not stop at local validation because of stale no-commit notes; use the authorization block above for this assigned task.",
            ].join("\n")
          : "";
        const message = [
          instruction,
          "",
          authorization,
          restoreMode ? "" : "",
          restoreMode,
          "",
          `AO session: ${config.sessionId}`,
          `AO task: ${issueId}`,
          isResume ? "AO restore: true" : "",
          config.prompt ? `AO prompt:\n${config.prompt}` : "",
        ]
          .filter(Boolean)
          .join("\n");
        const quotedWorkflow = shellEscape(workflow);
        const quotedMessage = shellEscape(message);

        const acknowledgeNote = isResume
          ? `dark-factory milestone=resume_started task=${issueId} phase=resume`
          : `dark-factory milestone=auto_feature_started task=${issueId} phase=auto_feature`;
        const resumeFallbackNote = `dark-factory milestone=resume_fallback task=${issueId} phase=resume`;
        const resumeRestartNote = `dark-factory milestone=resume_restart task=${issueId} phase=resume`;
        const completedNote = `dark-factory milestone=auto_feature_completed task=${issueId} phase=auto_feature`;
        const prOpenedNote = `dark-factory milestone=pr_opened task=${issueId} phase=auto_feature`;
        const mergeNote = `dark-factory milestone=auto_merge_preparing task=${issueId} phase=auto_merge`;
        const readyNote = `dark-factory milestone=ready_to_merge task=${issueId} phase=auto_merge`;
        const failedNote = `dark-factory milestone=failed task=${issueId} phase=auto_feature`;
        const mergeFailedNote = `dark-factory milestone=failed task=${issueId} phase=auto_merge`;

        return [
          "report_ao_status() {",
          "  report_status=\"$1\"",
          "  report_note=\"$2\"",
          "  shift 2",
          "  attempt=1",
          "  while [ \"$attempt\" -le 5 ]; do",
          `    if ${ao} report "$report_status" "$@" --note "$report_note"; then`,
          "      return 0",
          "    fi",
          "    attempt=$((attempt + 1))",
          "    sleep 2",
          "  done",
          "  return 1",
          "}",
          "report_ao_pr_status() {",
          "  report_status=\"$1\"",
          "  report_note=\"$2\"",
          "  pr_url=\"\"",
          "  pr_number=\"\"",
          "  if command -v gh >/dev/null 2>&1; then",
          "    pr_url=\"$(gh pr view --json url --jq .url 2>/dev/null || true)\"",
          "    pr_number=\"$(gh pr view --json number --jq .number 2>/dev/null || true)\"",
          "  fi",
          "  if [ -n \"$pr_url\" ] && [ -n \"$pr_number\" ]; then",
          "    report_ao_status \"$report_status\" \"$report_note\" --pr-url \"$pr_url\" --pr-number \"$pr_number\"",
          "  elif [ -n \"$pr_url\" ]; then",
          "    report_ao_status \"$report_status\" \"$report_note\" --pr-url \"$pr_url\"",
          "  else",
          "    report_ao_status \"$report_status\" \"$report_note\"",
          "  fi",
          "}",
          "report_archon_note() {",
          "  report_note=\"$1\"",
          "  if [ -n \"${dark_factory_archon_run_id:-}\" ]; then",
          "    report_note=\"$report_note archonRunId=$dark_factory_archon_run_id\"",
          "  fi",
          "  printf '%s' \"$report_note\"",
          "}",
          "run_dark_factory_stage() {",
          "  stage=\"$1\"",
          "  shift",
          "  \"$@\"",
          "  status=\"$?\"",
          "  if [ \"$status\" -ne 0 ]; then",
          "    printf '%s\\n' \"dark-factory command failed: stage=$stage status=$status command=$*\" >&2",
          "  fi",
          "  return \"$status\"",
          "}",
          "extract_archon_run_id() {",
          "  node -e \"const fs=require('node:fs');function extractJsonObject(input){const text=String(input??'');let best=null;for(let start=text.indexOf('{');start>=0;start=text.indexOf('{',start+1)){let depth=0,inString=false,escaping=false;for(let index=start;index<text.length;index++){const char=text[index];if(escaping){escaping=false;continue;}if(char.charCodeAt(0)===92){escaping=inString;continue;}if(char.charCodeAt(0)===34){inString=!inString;continue;}if(inString)continue;if(char==='{')depth++;else if(char==='}'){depth--;if(depth===0){const candidate=text.slice(start,index+1);try{const parsed=JSON.parse(candidate);if(!best||index>best.end||(index===best.end&&start<best.start))best={parsed,start,end:index};}catch{}break;}}}}if(!best)process.exit(1);return best.parsed;} const json=extractJsonObject(fs.readFileSync(0,'utf8')); const id=json.runId||json.id||json.workflow_id||json.workflowId||json.run?.id||json.run?.workflow_id||json.run?.workflowId||json.workflow?.id; if(!id) process.exit(1); process.stdout.write(String(id));\"",
          "}",
          "extract_archon_run_status() {",
          "  node -e \"const fs=require('node:fs');function extractJsonObject(input){const text=String(input??'');let best=null;for(let start=text.indexOf('{');start>=0;start=text.indexOf('{',start+1)){let depth=0,inString=false,escaping=false;for(let index=start;index<text.length;index++){const char=text[index];if(escaping){escaping=false;continue;}if(char.charCodeAt(0)===92){escaping=inString;continue;}if(char.charCodeAt(0)===34){inString=!inString;continue;}if(inString)continue;if(char==='{')depth++;else if(char==='}'){depth--;if(depth===0){const candidate=text.slice(start,index+1);try{const parsed=JSON.parse(candidate);if(!best||index>best.end||(index===best.end&&start<best.start))best={parsed,start,end:index};}catch{}break;}}}}if(!best)process.exit(1);return best.parsed;} const json=extractJsonObject(fs.readFileSync(0,'utf8')); const expected=String(process.env.DARK_FACTORY_ARCHON_RUN_ID||''); const idOf=(run)=>String(run?.id||run?.runId||run?.workflow_id||run?.workflowId||run?.run?.id||run?.run?.workflow_id||run?.run?.workflowId||run?.workflow?.id||''); const statusOf=(run)=>String(run?.status||run?.run?.status||''); const runs=Array.isArray(json)?json:Array.isArray(json.runs)?json.runs:[]; const run=runs.find((candidate)=>expected&&idOf(candidate)===expected)||(runs.length===1?runs[0]:json); const status=statusOf(run); if(!status) process.exit(1); process.stdout.write(status);\"",
          "}",
          "print_archon_output() {",
          "  output_label=\"$1\"",
          "  output_value=\"$2\"",
          "  if [ -n \"$output_value\" ]; then",
          "    printf '%s\\n' \"dark-factory $output_label output:\" >&2",
          "    printf '%s\\n' \"$output_value\" >&2",
          "  fi",
          "}",
          "read_archon_status_json() {",
          "  archon_get_output=\"$(archon workflow get \"$dark_factory_archon_run_id\" --json 2>&1)\"",
          "  archon_get_status=\"$?\"",
          "  if [ \"$archon_get_status\" -eq 0 ]; then",
          "    printf '%s' \"$archon_get_output\"",
          "    return 0",
          "  fi",
          "  archon_status_output=\"$(archon workflow status \"$dark_factory_archon_run_id\" --json 2>&1)\"",
          "  archon_status_status=\"$?\"",
          "  if [ \"$archon_status_status\" -eq 0 ]; then",
          "    printf '%s' \"$archon_status_output\"",
          "    return 0",
          "  fi",
          "  print_archon_output \"archon workflow get\" \"$archon_get_output\"",
          "  print_archon_output \"archon workflow status\" \"$archon_status_output\"",
          "  return \"$archon_status_status\"",
          "}",
          "read_archon_log_status() {",
          "  DARK_FACTORY_ARCHON_RUN_ID=\"$dark_factory_archon_run_id\" node <<'NODE'",
          "const fs = require('node:fs');",
          "const path = `.archon/logs/${process.env.DARK_FACTORY_ARCHON_RUN_ID}.jsonl`;",
          "if (!process.env.DARK_FACTORY_ARCHON_RUN_ID || !fs.existsSync(path)) process.exit(1);",
          "const lines = fs.readFileSync(path, 'utf8').trim().split('\\n').filter(Boolean);",
          "for (let index = lines.length - 1; index >= 0; index -= 1) {",
          "  let event;",
          "  try { event = JSON.parse(lines[index]); } catch { continue; }",
          "  if (event.type === 'workflow_complete') {",
          "    process.stdout.write('completed');",
          "    process.exit(0);",
          "  }",
          "  if (event.type === 'workflow_failed' || event.type === 'node_failed') {",
          "    process.stdout.write('failed');",
          "    process.exit(0);",
          "  }",
          "}",
          "process.exit(1);",
          "NODE",
          "}",
          "discover_active_archon_run_id_by_path() {",
          "  archon_status_output=\"$(archon workflow status --cwd \"$(pwd -P)\" --json 2>&1)\"",
          "  archon_status_status=\"$?\"",
          "  if [ \"$archon_status_status\" -ne 0 ]; then",
          "    return \"$archon_status_status\"",
          "  fi",
          "  DARK_FACTORY_ARCHON_STATUS_JSON=\"$archon_status_output\" \\",
          "  DARK_FACTORY_WORKING_PATH=\"$(pwd -P)\" \\",
          "  DARK_FACTORY_ARCHON_IGNORE_RUN_ID=\"${DARK_FACTORY_ARCHON_IGNORE_RUN_ID:-}\" \\",
          "  node <<'NODE'",
          "function extractJsonObject(input) {",
          "  const text = String(input ?? '');",
          "  let best = null;",
          "  for (let start = text.indexOf('{'); start >= 0; start = text.indexOf('{', start + 1)) {",
          "    let depth = 0;",
          "    let inString = false;",
          "    let escaping = false;",
          "    for (let index = start; index < text.length; index++) {",
          "      const char = text[index];",
          "      if (escaping) {",
          "        escaping = false;",
          "        continue;",
          "      }",
          "      if (char.charCodeAt(0) === 92) {",
          "        escaping = inString;",
          "        continue;",
          "      }",
          "      if (char.charCodeAt(0) === 34) {",
          "        inString = !inString;",
          "        continue;",
          "      }",
          "      if (inString) continue;",
          "      if (char === '{') depth++;",
          "      else if (char === '}') {",
          "        depth--;",
          "        if (depth === 0) {",
          "          const candidate = text.slice(start, index + 1);",
          "          try {",
          "            const parsed = JSON.parse(candidate);",
          "            if (!best || index > best.end || (index === best.end && start < best.start)) best = { parsed, start, end: index };",
          "          } catch {}",
          "          break;",
          "        }",
          "      }",
          "    }",
          "  }",
          "  if (!best) process.exit(1);",
          "  return best.parsed;",
          "}",
          "function listRuns(data) {",
          "  if (Array.isArray(data)) return data;",
          "  if (!data || typeof data !== 'object') return [];",
          "  const keys = ['runs', 'workflows', 'active_runs', 'activeRuns', 'items', 'records'];",
          "  for (const key of keys) {",
          "    if (Array.isArray(data[key])) return data[key];",
          "  }",
          "  return [data];",
          "}",
          "function idOf(run) {",
          "  return run?.id || run?.runId || run?.workflow_id || run?.workflowId || run?.run?.id || run?.run?.workflow_id || run?.run?.workflowId || run?.workflow?.id || run?.workflow?.workflow_id || run?.workflow?.workflowId;",
          "}",
          "function statusOf(run) {",
          "  return String(run?.status || run?.run?.status || run?.workflow?.status || '').toLowerCase();",
          "}",
          "function workingPathOf(run) {",
          "  return String(run?.working_path || run?.workingPath || run?.cwd || run?.path || run?.run?.working_path || run?.run?.workingPath || run?.run?.cwd || run?.workflow?.working_path || run?.workflow?.workingPath || run?.workflow?.cwd || '');",
          "}",
          "const data = extractJsonObject(process.env.DARK_FACTORY_ARCHON_STATUS_JSON || '{}');",
          "const expectedPath = process.env.DARK_FACTORY_WORKING_PATH || '';",
          "const ignoredId = process.env.DARK_FACTORY_ARCHON_IGNORE_RUN_ID || '';",
          "const activeStatuses = new Set([\"running\", \"pending\", \"paused\", \"needs_input\", \"needs-input\", \"waiting\", \"blocked\"]);",
          "if (!expectedPath) process.exit(1);",
          "for (const run of listRuns(data)) {",
          "  const id = idOf(run);",
          "  const status = statusOf(run);",
          "  const workingPath = workingPathOf(run);",
          "  if (!id || !activeStatuses.has(status) || !workingPath || workingPath !== expectedPath) continue;",
          "  if (ignoredId && String(id) === ignoredId) continue;",
          "  process.stdout.write(String(id));",
          "  process.exit(0);",
          "}",
          "process.exit(1);",
          "NODE",
          "}",
          "abandon_stale_active_archon_runs_by_path() {",
          "  archon_stale_status_output=\"$(archon workflow status --cwd \"$(pwd -P)\" --json 2>&1)\"",
          "  archon_stale_status=\"$?\"",
          "  if [ \"$archon_stale_status\" -ne 0 ]; then",
          "    return 0",
          "  fi",
          "  stale_archon_run_ids=\"$(",
          "  DARK_FACTORY_ARCHON_STATUS_JSON=\"$archon_stale_status_output\" \\",
          "  DARK_FACTORY_WORKING_PATH=\"$(pwd -P)\" \\",
          "  DARK_FACTORY_ARCHON_ACTIVE_STALE_SECONDS=\"${DARK_FACTORY_ARCHON_ACTIVE_STALE_SECONDS:-600}\" \\",
          "  node <<'NODE'",
          "const fs = require('node:fs');",
          "function extractJsonObject(input) {",
          "  const text = String(input ?? '');",
          "  let best = null;",
          "  for (let start = text.indexOf('{'); start >= 0; start = text.indexOf('{', start + 1)) {",
          "    let depth = 0;",
          "    let inString = false;",
          "    let escaping = false;",
          "    for (let index = start; index < text.length; index++) {",
          "      const char = text[index];",
          "      if (escaping) {",
          "        escaping = false;",
          "        continue;",
          "      }",
          "      if (char.charCodeAt(0) === 92) {",
          "        escaping = inString;",
          "        continue;",
          "      }",
          "      if (char.charCodeAt(0) === 34) {",
          "        inString = !inString;",
          "        continue;",
          "      }",
          "      if (inString) continue;",
          "      if (char === '{') depth++;",
          "      else if (char === '}') {",
          "        depth--;",
          "        if (depth === 0) {",
          "          const candidate = text.slice(start, index + 1);",
          "          try {",
          "            const parsed = JSON.parse(candidate);",
          "            if (!best || index > best.end || (index === best.end && start < best.start)) best = { parsed, start, end: index };",
          "          } catch {}",
          "          break;",
          "        }",
          "      }",
          "    }",
          "  }",
          "  if (!best) process.exit(0);",
          "  return best.parsed;",
          "}",
          "function listRuns(data) {",
          "  if (Array.isArray(data)) return data;",
          "  if (!data || typeof data !== 'object') return [];",
          "  for (const key of ['runs', 'workflows', 'active_runs', 'activeRuns', 'items', 'records']) {",
          "    if (Array.isArray(data[key])) return data[key];",
          "  }",
          "  return [data];",
          "}",
          "function idOf(run) { return run?.id || run?.runId || run?.workflow_id || run?.workflowId || run?.run?.id || run?.workflow?.id; }",
          "function statusOf(run) { return String(run?.status || run?.run?.status || run?.workflow?.status || '').toLowerCase(); }",
          "function workingPathOf(run) { return String(run?.working_path || run?.workingPath || run?.cwd || run?.path || run?.run?.working_path || run?.run?.workingPath || run?.run?.cwd || run?.workflow?.working_path || run?.workflow?.workingPath || run?.workflow?.cwd || ''); }",
          "function timestampOf(run) {",
          "  const raw = String(run?.last_activity_at || run?.lastActivityAt || run?.updated_at || run?.updatedAt || run?.started_at || run?.startedAt || '');",
          "  if (!raw) return 0;",
          "  const normalized = raw.includes('T') ? raw : raw.replace(' ', 'T');",
          "  const time = Date.parse(normalized.endsWith('Z') ? normalized : `${normalized}Z`);",
          "  return Number.isFinite(time) ? time : 0;",
          "}",
          "function hasLiveAgentProcess(expectedPath) {",
          "  if (process.platform !== 'linux') return true;",
          "  let entries;",
          "  try { entries = fs.readdirSync('/proc'); } catch { return true; }",
          "  for (const entry of entries) {",
          "    if (!/^\\d+$/.test(entry) || Number(entry) === process.pid) continue;",
          "    let cwd;",
          "    try { cwd = fs.realpathSync(`/proc/${entry}/cwd`); } catch { continue; }",
          "    if (cwd !== expectedPath) continue;",
          "    let argv0 = '';",
          "    try {",
          "      argv0 = fs.readFileSync(`/proc/${entry}/cmdline`, 'utf8').split('\\u0000').filter(Boolean)[0] || '';",
          "    } catch {}",
          "    const executable = argv0.split('/').pop() || '';",
          "    if (/^(archon|codex|claude|opencode|cursor-agent)$/i.test(executable)) return true;",
          "  }",
          "  return false;",
          "}",
          "const expectedPath = process.env.DARK_FACTORY_WORKING_PATH || '';",
          "const staleSeconds = Math.max(60, Number.parseInt(process.env.DARK_FACTORY_ARCHON_ACTIVE_STALE_SECONDS || '600', 10) || 600);",
          "const activeStatuses = new Set(['running', 'pending', 'paused', 'needs_input', 'needs-input', 'waiting', 'blocked']);",
          "if (!expectedPath) process.exit(0);",
          "const liveAgentProcess = hasLiveAgentProcess(expectedPath);",
          "const now = Date.now();",
          "const staleIds = [];",
          "for (const run of listRuns(extractJsonObject(process.env.DARK_FACTORY_ARCHON_STATUS_JSON || '{}'))) {",
          "  const id = idOf(run);",
          "  const status = statusOf(run);",
          "  const timestamp = timestampOf(run);",
          "  if (!id || !activeStatuses.has(status) || workingPathOf(run) !== expectedPath) continue;",
          "  const ageSeconds = timestamp ? (now - timestamp) / 1000 : 0;",
          "  const detachedActive = status === 'running' || status === 'paused';",
          "  const pendingTimedOut = status === 'pending' && timestamp && ageSeconds >= staleSeconds;",
          "  if (!liveAgentProcess && (detachedActive || pendingTimedOut)) staleIds.push(String(id));",
          "}",
          "if (staleIds.length > 0) process.stdout.write(staleIds.join('\\n'));",
          "NODE",
          "  )\"",
          "  if [ -z \"$stale_archon_run_ids\" ]; then",
          "    return 0",
          "  fi",
          "  printf '%s\\n' \"$stale_archon_run_ids\" | while IFS= read -r dark_factory_stale_archon_run_id; do",
          "    if [ -n \"$dark_factory_stale_archon_run_id\" ]; then",
          "      archon workflow abandon \"$dark_factory_stale_archon_run_id\" --json >/dev/null 2>&1 || true",
          "    fi",
          "  done",
          "}",
          "discover_archon_run_id_from_logs() {",
          "  DARK_FACTORY_ARCHON_LOG_DIR=\"$(pwd -P)/.archon/logs\" \\",
          "  DARK_FACTORY_WORKFLOW_NAME=\"$workflow_name\" \\",
          "  DARK_FACTORY_WORKFLOW_MESSAGE=\"$workflow_message\" \\",
          "  DARK_FACTORY_SESSION_ID=\"$dark_factory_session_id\" \\",
          "  DARK_FACTORY_ISSUE_ID=\"$dark_factory_issue_id\" \\",
          "  node <<'NODE'",
          "const fs = require('node:fs');",
          "const path = require('node:path');",
          "const logDir = process.env.DARK_FACTORY_ARCHON_LOG_DIR || '';",
          "const expectedWorkflow = process.env.DARK_FACTORY_WORKFLOW_NAME || '';",
          "const expectedMessage = process.env.DARK_FACTORY_WORKFLOW_MESSAGE || '';",
          "const sessionId = process.env.DARK_FACTORY_SESSION_ID || '';",
          "const issueId = process.env.DARK_FACTORY_ISSUE_ID || '';",
          "const ignoredId = process.env.DARK_FACTORY_ARCHON_IGNORE_RUN_ID || '';",
          "const allowFailed = process.env.DARK_FACTORY_ARCHON_ALLOW_FAILED_DISCOVERY === '1';",
          "function readJsonLine(line) {",
          "  try { return JSON.parse(line); } catch { return null; }",
          "}",
          "function scoreLog(start, last) {",
          "  if (!start || start.type !== 'workflow_start') return 0;",
          "  if (String(start.workflow_name || '') !== expectedWorkflow) return 0;",
          "  const content = String(start.content || '');",
          "  const exact = content === expectedMessage;",
          "  const marker = sessionId && issueId && content.includes(`AO session: ${sessionId}`) && content.includes(`AO task: ${issueId}`);",
          "  if (!exact && !marker) return 0;",
          "  if (!allowFailed && ['workflow_error', 'workflow_failed', 'node_error', 'node_failed'].includes(String(last?.type || ''))) return 0;",
          "  let score = exact ? 4 : 2;",
          "  if (last?.type === 'workflow_complete') score += 1;",
          "  return score;",
          "}",
          "if (!logDir || !fs.existsSync(logDir)) process.exit(1);",
          "const candidates = fs.readdirSync(logDir)",
          "  .filter((name) => name.endsWith('.jsonl'))",
          "  .map((name) => {",
          "    const filePath = path.join(logDir, name);",
          "    let stat;",
          "    try { stat = fs.statSync(filePath); } catch { return null; }",
          "    const lines = fs.readFileSync(filePath, 'utf8').trim().split('\\n').filter(Boolean);",
          "    if (lines.length === 0) return null;",
          "    const start = readJsonLine(lines[0]);",
          "    const last = readJsonLine(lines[lines.length - 1]);",
          "    const score = scoreLog(start, last);",
          "    if (!score) return null;",
          "    const id = start.workflow_id || name.replace(/\\.jsonl$/, '');",
          "    if (ignoredId && String(id) === ignoredId) return null;",
          "    return {",
          "      id,",
          "      score,",
          "      mtimeMs: stat.mtimeMs,",
          "    };",
          "  })",
          "  .filter(Boolean)",
          "  .sort((left, right) => right.score - left.score || right.mtimeMs - left.mtimeMs);",
          "if (!candidates[0]?.id) process.exit(1);",
          "process.stdout.write(String(candidates[0].id));",
          "NODE",
          "}",
          "discover_archon_run_id() {",
          "  archon_runs_output=\"$(archon workflow runs --json --limit \"${DARK_FACTORY_ARCHON_DISCOVERY_LIMIT:-25}\" 2>&1)\"",
          "  archon_runs_status=\"$?\"",
          "  if [ \"$archon_runs_status\" -ne 0 ]; then",
          "    dark_factory_archon_log_id=\"$(discover_archon_run_id_from_logs || true)\"",
          "    if [ -n \"$dark_factory_archon_log_id\" ]; then",
          "      printf '%s' \"$dark_factory_archon_log_id\"",
          "      return 0",
          "    fi",
          "    print_archon_output \"archon workflow runs\" \"$archon_runs_output\"",
          "    return \"$archon_runs_status\"",
          "  fi",
          "  DARK_FACTORY_ARCHON_RUNS_JSON=\"$archon_runs_output\" \\",
          "  DARK_FACTORY_WORKFLOW_NAME=\"$workflow_name\" \\",
          "  DARK_FACTORY_WORKFLOW_MESSAGE=\"$workflow_message\" \\",
          "  DARK_FACTORY_WORKING_PATH=\"$(pwd -P)\" \\",
          "  DARK_FACTORY_SESSION_ID=\"$dark_factory_session_id\" \\",
          "  DARK_FACTORY_ISSUE_ID=\"$dark_factory_issue_id\" \\",
          "  DARK_FACTORY_ARCHON_IGNORE_RUN_ID=\"${DARK_FACTORY_ARCHON_IGNORE_RUN_ID:-}\" \\",
          "  node <<'NODE'",
          "function extractJsonObject(input) {",
          "  const text = String(input ?? '');",
          "  let best = null;",
          "  for (let start = text.indexOf('{'); start >= 0; start = text.indexOf('{', start + 1)) {",
          "    let depth = 0;",
          "    let inString = false;",
          "    let escaping = false;",
          "    for (let index = start; index < text.length; index++) {",
          "      const char = text[index];",
          "      if (escaping) {",
          "        escaping = false;",
          "        continue;",
          "      }",
          "      if (char.charCodeAt(0) === 92) {",
          "        escaping = inString;",
          "        continue;",
          "      }",
          "      if (char.charCodeAt(0) === 34) {",
          "        inString = !inString;",
          "        continue;",
          "      }",
          "      if (inString) continue;",
          "      if (char === '{') depth++;",
          "      else if (char === '}') {",
          "        depth--;",
          "        if (depth === 0) {",
          "          const candidate = text.slice(start, index + 1);",
          "          try {",
          "            const parsed = JSON.parse(candidate);",
          "            if (!best || index > best.end || (index === best.end && start < best.start)) best = { parsed, start, end: index };",
          "          } catch {}",
          "          break;",
          "        }",
          "      }",
          "    }",
          "  }",
          "  if (!best) process.exit(1);",
          "  return best.parsed;",
          "}",
          "const data = extractJsonObject(process.env.DARK_FACTORY_ARCHON_RUNS_JSON || '{}');",
          "const runs = Array.isArray(data) ? data : Array.isArray(data.runs) ? data.runs : [];",
          "const expectedWorkflow = process.env.DARK_FACTORY_WORKFLOW_NAME || '';",
          "const expectedMessage = process.env.DARK_FACTORY_WORKFLOW_MESSAGE || '';",
          "const expectedPath = process.env.DARK_FACTORY_WORKING_PATH || '';",
          "const sessionId = process.env.DARK_FACTORY_SESSION_ID || '';",
          "const issueId = process.env.DARK_FACTORY_ISSUE_ID || '';",
          "const ignoredId = process.env.DARK_FACTORY_ARCHON_IGNORE_RUN_ID || '';",
          "for (const run of runs) {",
          "  const status = String(run.status || run.run?.status || '').toLowerCase();",
          "  if (!(status === \"running\" || status === \"pending\" || status === \"paused\" || status === \"needs_input\" || status === \"needs-input\" || status === \"waiting\" || status === \"blocked\" || status === \"completed\" || status === \"success\" || status === \"succeeded\")) continue;",
          "  const workflow = String(run.workflow_name || run.workflowName || run.workflow?.name || run.name || '');",
          "  if (workflow !== expectedWorkflow) continue;",
          "  const message = String(run.user_message || run.userMessage || run.message || '');",
          "  const workingPath = String(run.working_path || run.workingPath || run.cwd || '');",
          "  const messageMatches = message === expectedMessage || (sessionId && issueId && message.includes(`AO session: ${sessionId}`) && message.includes(`AO task: ${issueId}`));",
          "  const pathMatches = !workingPath || !expectedPath || workingPath === expectedPath;",
          "  if (!messageMatches || !pathMatches) continue;",
          "  const id = run.id || run.runId || run.workflow_id || run.workflowId || run.run?.id || run.workflow?.id;",
          "  if (ignoredId && String(id) === ignoredId) continue;",
          "  if (id) {",
          "    process.stdout.write(String(id));",
          "    process.exit(0);",
          "  }",
          "}",
          "process.exit(1);",
          "NODE",
          "  dark_factory_archon_discovery_status=\"$?\"",
          "  if [ \"$dark_factory_archon_discovery_status\" -eq 0 ]; then",
          "    return 0",
          "  fi",
          "  discover_archon_run_id_from_logs",
          "}",
          "activate_persisted_archon_home() {",
          "  if [ ! -f \"$dark_factory_archon_home_pointer\" ]; then",
          "    return 0",
          "  fi",
          "  persisted_archon_home=\"$(cat \"$dark_factory_archon_home_pointer\" 2>/dev/null || true)\"",
          "  case \"$persisted_archon_home\" in",
          "    \"$dark_factory_archon_homes_dir\"/*)",
          "      if [ -d \"$persisted_archon_home\" ]; then",
          "        export ARCHON_HOME=\"$persisted_archon_home\"",
          "      fi",
          "      ;;",
          "    *)",
          "      printf '%s\\n' \"dark-factory ignored invalid Archon home pointer: $persisted_archon_home\" >&2",
          "      ;;",
          "  esac",
          "}",
          "activate_fresh_archon_home() {",
          "  mkdir -p \"$dark_factory_archon_homes_dir\" \"$(dirname \"$dark_factory_archon_home_pointer\")\" || return 1",
          "  fresh_archon_home=\"$dark_factory_archon_homes_dir/restart-$(date +%s%N)-$$\"",
          "  mkdir \"$fresh_archon_home\" || return 1",
          "  chmod 700 \"$fresh_archon_home\" || return 1",
          "  for shared_name in workflows scripts config.yaml .env; do",
          "    if [ -e \"$dark_factory_archon_source_home/$shared_name\" ]; then",
          "      ln -s \"$dark_factory_archon_source_home/$shared_name\" \"$fresh_archon_home/$shared_name\" || return 1",
          "    fi",
          "  done",
          "  if [ ! -e \"$fresh_archon_home/workflows\" ]; then",
          "    printf '%s\\n' \"dark-factory could not share Archon workflows from $dark_factory_archon_source_home\" >&2",
          "    return 1",
          "  fi",
          "  printf '%s\\n' \"$fresh_archon_home\" > \"$dark_factory_archon_home_pointer\" || return 1",
          "  export ARCHON_HOME=\"$fresh_archon_home\"",
          "}",
          "start_archon_run() {",
          "  abandon_stale_active_archon_runs_by_path || true",
          "  archon_output=\"$(archon workflow run \"$workflow_name\" --no-worktree --json \"$workflow_message\" 2>&1)\"",
          "  archon_start_status=\"$?\"",
          "  dark_factory_archon_run_id=\"$(printf '%s' \"$archon_output\" | extract_archon_run_id 2>/dev/null || true)\"",
          "  if [ -z \"$dark_factory_archon_run_id\" ]; then",
          "    dark_factory_archon_run_id=\"$(discover_active_archon_run_id_by_path || true)\"",
          "  fi",
          "  if [ -z \"$dark_factory_archon_run_id\" ]; then",
          "    dark_factory_archon_run_id=\"$(discover_archon_run_id || true)\"",
          "  fi",
          "  if [ -z \"$dark_factory_archon_run_id\" ]; then",
          "    print_archon_output \"archon workflow start\" \"$archon_output\"",
          "    if [ \"$archon_start_status\" -ne 0 ]; then",
          "      return \"$archon_start_status\"",
          "    fi",
          "    dark_factory_archon_run_completed=1",
          "    dark_factory_archon_run_active=0",
          "    return 0",
          "  fi",
          "  export DARK_FACTORY_ARCHON_RUN_ID=\"$dark_factory_archon_run_id\"",
          "  dark_factory_archon_run_active=1",
          "}",
          "restart_archon_run() {",
          "  previous_archon_run_id=\"$dark_factory_archon_run_id\"",
          "  if [ -n \"$previous_archon_run_id\" ]; then",
          "    archon workflow abandon \"$previous_archon_run_id\" --json >/dev/null 2>&1 || true",
          "  fi",
          "  dark_factory_archon_run_id=\"\"",
          "  unset DARK_FACTORY_ARCHON_RUN_ID",
          "  activate_fresh_archon_home || return $?",
          "  original_workflow_message=\"$workflow_message\"",
          "  workflow_message=\"${workflow_message}",
          "Dark Factory restart: $(date -u +%Y-%m-%dT%H:%M:%SZ)\"",
          "  DARK_FACTORY_ARCHON_IGNORE_RUN_ID=\"$previous_archon_run_id\" start_archon_run",
          "  restart_status=\"$?\"",
          "  workflow_message=\"$original_workflow_message\"",
          "  return \"$restart_status\"",
          "}",
          "wait_archon_run() {",
          "  if [ \"${dark_factory_archon_run_completed:-0}\" = \"1\" ]; then",
          "    return 0",
          "  fi",
          "  while true; do",
          "    archon_status_json=\"$(read_archon_status_json)\" || return $?",
          "    archon_status=\"$(printf '%s' \"$archon_status_json\" | extract_archon_run_status 2>/dev/null || read_archon_log_status)\" || return 1",
          "    case \"$archon_status\" in",
          "      completed|success|succeeded)",
          "        dark_factory_archon_run_active=0",
          "        return 0",
          "        ;;",
          "      failed|error|errored|cancelled|abandoned|needs_input|needs-input|waiting|blocked|paused)",
          "        dark_factory_archon_run_active=0",
          "        printf '%s\\n' \"$archon_status_json\" >&2",
          "        return 1",
          "        ;;",
          "      *)",
          "        sleep \"${DARK_FACTORY_ARCHON_POLL_SECONDS:-10}\"",
          "        ;;",
          "    esac",
          "  done",
          "}",
          "resume_archon_run() {",
          "  archon_resume_output=\"$(archon workflow resume \"$dark_factory_archon_run_id\" --json 2>&1)\"",
          "  archon_resume_status=\"$?\"",
          "  resumed_archon_run_id=\"$(printf '%s' \"$archon_resume_output\" | extract_archon_run_id 2>/dev/null || true)\"",
          "  if [ \"$archon_resume_status\" -ne 0 ] && [ -z \"$resumed_archon_run_id\" ]; then",
          "    print_archon_output \"archon workflow resume\" \"$archon_resume_output\"",
          "    return \"$archon_resume_status\"",
          "  fi",
          "  if [ -n \"$resumed_archon_run_id\" ]; then",
          "    dark_factory_archon_run_id=\"$resumed_archon_run_id\"",
          "    export DARK_FACTORY_ARCHON_RUN_ID=\"$dark_factory_archon_run_id\"",
          "  fi",
          "  dark_factory_archon_run_active=1",
          "}",
          "archon_run_resumable() {",
          "  archon_resumable_json=\"$(read_archon_status_json)\" || { archon_resumable_status=unknown; return 1; }",
          "  archon_resumable_status=\"$(printf '%s' \"$archon_resumable_json\" | extract_archon_run_status 2>/dev/null || read_archon_log_status)\" || { archon_resumable_status=unknown; return 1; }",
          "  case \"$archon_resumable_status\" in",
          "    failed|paused|needs_input|needs-input|waiting|blocked)",
          "      return 0",
          "      ;;",
          "    cancelled|abandoned)",
          "      return 1",
          "      ;;",
          "    *)",
          "      return 1",
          "      ;;",
          "  esac",
          "}",
          "abandon_archon_run() {",
          "  if [ \"${dark_factory_archon_run_active:-0}\" = \"1\" ] && [ -n \"${dark_factory_archon_run_id:-}\" ]; then",
          "    archon workflow abandon \"$dark_factory_archon_run_id\" --json >/dev/null 2>&1 || true",
          "    dark_factory_archon_run_active=0",
          "  fi",
          "}",
          `dark_factory_project_id=${shellEscape(darkFactoryProjectId)}`,
          `dark_factory_session_id=${shellEscape(sessionId)}`,
          `dark_factory_issue_id=${shellEscape(issueId)}`,
          `dark_factory_api_port=${shellEscape(ports.apiPort)}`,
          `dark_factory_web_port=${shellEscape(ports.webPort)}`,
          `workflow_name=${quotedWorkflow}`,
          `workflow_message=${quotedMessage}`,
          "dark_factory_archon_source_home=\"${DARK_FACTORY_ARCHON_SOURCE_HOME:-${ARCHON_HOME:-$HOME/.archon}}\"",
          "dark_factory_archon_homes_dir=\"$(pwd -P)/.archon/dark-factory-homes\"",
          "dark_factory_archon_home_pointer=\"$(pwd -P)/.archon/state/dark-factory-archon-home\"",
          "activate_persisted_archon_home || exit 1",
          "dark_factory_archon_run_id=\"${DARK_FACTORY_ARCHON_RUN_ID:-}\"",
          "dark_factory_archon_run_active=0",
          "dark_factory_archon_run_completed=0",
          "trap 'abandon_archon_run; exit 130' INT TERM",
          "dark_factory_selected_ports=\"$(node " + shellEscape(runtimeContextScript) + " resolve " + [
            "--cwd \"$(pwd -P)\"",
            `--project-id ${shellEscape(darkFactoryProjectId)}`,
            `--session-id ${shellEscape(sessionId)}`,
            `--issue-id ${shellEscape(issueId)}`,
            "--initial-api-port \"$dark_factory_api_port\"",
            ...(isResume ? ["--restore"] : []),
            "--shell",
          ].join(" ") + ")\" || exit 1",
          "eval \"$dark_factory_selected_ports\"",
          `export DARK_FACTORY_PROJECT_ID=${shellEscape(darkFactoryProjectId)}`,
          `export DARK_FACTORY_SESSION_ID=${shellEscape(sessionId)}`,
          `export DARK_FACTORY_ISSUE_ID=${shellEscape(issueId)}`,
          `export COMPOSE_PROJECT_NAME=${shellEscape(composeName)}`,
          `export CHROME_PROFILE_MODE=${shellEscape("temp")}`,
          "export PORT=\"$dark_factory_api_port\"",
          "export WEB_PORT=\"$dark_factory_web_port\"",
          ...runtimeEnvExportLines(agentConfig),
          "export DARK_FACTORY_API_PORT=\"$dark_factory_api_port\"",
          "export DARK_FACTORY_WEB_PORT=\"$dark_factory_web_port\"",
          ...(isResume ? [
            "restore_should_prepare_existing_pr() {",
            "  if ! command -v gh >/dev/null 2>&1 || ! command -v git >/dev/null 2>&1; then",
            "    return 1",
            "  fi",
            "  pr_state=\"$(gh pr view --json state --jq '.state' 2>/dev/null || true)\"",
            "  if [ \"$pr_state\" != \"OPEN\" ]; then",
            "    return 1",
            "  fi",
            "  merge_head_path=\"$(git rev-parse --git-path MERGE_HEAD 2>/dev/null || true)\"",
            "  if [ -n \"$merge_head_path\" ] && [ -f \"$merge_head_path\" ]; then",
            "    return 0",
            "  fi",
            "  git diff --quiet || return 1",
            "  git diff --cached --quiet || return 1",
            "  local_head=\"$(git rev-parse HEAD 2>/dev/null || true)\"",
            "  upstream_head=\"$(git rev-parse '@{upstream}' 2>/dev/null || true)\"",
            "  [ -n \"$local_head\" ] && [ \"$local_head\" = \"$upstream_head\" ]",
            "}",
          ] : []),
          "write_dark_factory_ready() {",
          "  if [ -z \"$dark_factory_project_id\" ]; then",
          "    printf '%s\\n' 'dark-factory ready artifact failed: missing project id' >&2",
          "    return 1",
          "  fi",
          "  if ! command -v gh >/dev/null 2>&1; then",
          "    printf '%s\\n' 'dark-factory ready artifact failed: gh is missing' >&2",
          "    return 1",
          "  fi",
          "  branch=\"$(git branch --show-current 2>/dev/null || true)\"",
          "  local_head=\"$(git rev-parse HEAD 2>/dev/null || true)\"",
          "  if [ -z \"$branch\" ] || [ -z \"$local_head\" ]; then",
          "    printf '%s\\n' 'dark-factory ready artifact failed: missing branch or local HEAD' >&2",
          "    return 1",
          "  fi",
          "  git fetch origin \"$branch\" --quiet || return 1",
          "  remote_head=\"$(git rev-parse \"origin/$branch\" 2>/dev/null || true)\"",
          "  if [ -z \"$remote_head\" ]; then",
          "    printf '%s\\n' 'dark-factory ready artifact failed: missing remote HEAD' >&2",
          "    return 1",
          "  fi",
          "  pr_json=\"$(gh pr view --json number,url,state,headRefOid,mergeStateStatus 2>/dev/null)\" || return 1",
          "  ready_dir=\"${AGENT_ORCHESTRATOR_HOME:-$HOME/.agent-orchestrator}/projects/$dark_factory_project_id/sessions\"",
          `  ready_path="$ready_dir/${sessionId}.ready.json"`,
          "  mkdir -p \"$ready_dir\" || return 1",
          "  DARK_FACTORY_READY_PATH=\"$ready_path\" \\",
          "  DARK_FACTORY_PROJECT_ID=\"$dark_factory_project_id\" \\",
          "  DARK_FACTORY_SESSION_ID=\"$dark_factory_session_id\" \\",
          "  DARK_FACTORY_ISSUE_ID=\"$dark_factory_issue_id\" \\",
          "  DARK_FACTORY_BRANCH=\"$branch\" \\",
          "  DARK_FACTORY_LOCAL_HEAD=\"$local_head\" \\",
          "  DARK_FACTORY_REMOTE_HEAD=\"$remote_head\" \\",
          "  DARK_FACTORY_PR_JSON=\"$pr_json\" \\",
          "  DARK_FACTORY_ARCHON_RUN_ID=\"$dark_factory_archon_run_id\" \\",
          "  node <<'NODE'",
          "const fs = require('node:fs');",
          "const readText = (...paths) => {",
          "  const path = paths.find((candidate) => fs.existsSync(candidate));",
          "  return path ? fs.readFileSync(path, 'utf8').trim() || null : null;",
          "};",
          "const readJson = (path) => {",
          "  if (!fs.existsSync(path)) return null;",
          "  try { return JSON.parse(fs.readFileSync(path, 'utf8')); } catch { return null; }",
          "};",
          "const pr = JSON.parse(process.env.DARK_FACTORY_PR_JSON || '{}');",
          "const artifact = {",
          "  version: 2,",
          "  projectId: process.env.DARK_FACTORY_PROJECT_ID,",
          "  sessionId: process.env.DARK_FACTORY_SESSION_ID,",
          "  issueId: process.env.DARK_FACTORY_ISSUE_ID,",
          "  archonRunId: process.env.DARK_FACTORY_ARCHON_RUN_ID || null,",
          "  transitionKey: [process.env.DARK_FACTORY_PROJECT_ID, process.env.DARK_FACTORY_ISSUE_ID, pr.number ?? 'no-pr', process.env.DARK_FACTORY_REMOTE_HEAD].join(':'),",
          "  branch: process.env.DARK_FACTORY_BRANCH,",
          "  localHead: process.env.DARK_FACTORY_LOCAL_HEAD,",
          "  remoteHead: process.env.DARK_FACTORY_REMOTE_HEAD,",
          "  pr,",
          "  qa: {",
          "    status: readText('.archon/state/qa-status.txt', '.archon/state/frontend-qa-status.txt'),",
          "    result: readText('.archon/state/qa-result.md', '.archon/state/frontend-qa-result.md'),",
          "  },",
          "  reviewCycle: readJson('.archon/.state/review-cycle.json'),",
          "  preparedAt: new Date().toISOString(),",
          "};",
          "fs.writeFileSync(process.env.DARK_FACTORY_READY_PATH, `${JSON.stringify(artifact, null, 2)}\\n`);",
          "NODE",
          "}",
          ...(isResume ? [
            "dark_factory_restore_direct_prepare=0",
            "if restore_should_prepare_existing_pr; then",
            "  dark_factory_restore_direct_prepare=1",
            "fi",
            "status=0",
            "if [ \"$dark_factory_restore_direct_prepare\" = \"1\" ]; then",
            `  report_ao_pr_status pr-created "$(report_archon_note ${shellEscape(prOpenedNote)})" || true`,
            "else",
            "  abandon_stale_active_archon_runs_by_path || true",
            "  if [ -z \"$dark_factory_archon_run_id\" ]; then",
            "    dark_factory_archon_run_id=\"$(discover_active_archon_run_id_by_path || true)\"",
            "    if [ -n \"$dark_factory_archon_run_id\" ]; then",
            "      export DARK_FACTORY_ARCHON_RUN_ID=\"$dark_factory_archon_run_id\"",
            "    fi",
            "  fi",
            "  if [ -n \"$dark_factory_archon_run_id\" ]; then",
            `  report_ao_status working "$(report_archon_note ${shellEscape(acknowledgeNote)})" || true`,
            "    if archon_run_resumable; then",
            "      run_dark_factory_stage \"archon workflow resume\" resume_archon_run",
            "      status=$?",
            "      if [ \"$status\" -eq 0 ]; then",
            "        run_dark_factory_stage \"archon workflow wait\" wait_archon_run",
            "        status=$?",
            "      fi",
            "    elif [ \"$archon_resumable_status\" = \"running\" ] || [ \"$archon_resumable_status\" = \"pending\" ]; then",
            "      dark_factory_archon_run_active=1",
            "      run_dark_factory_stage \"archon workflow wait\" wait_archon_run",
            "      status=$?",
            "    else",
            "      status=1",
            "    fi",
            "    if [ \"$status\" -ne 0 ]; then",
            "      run_dark_factory_stage \"archon workflow restart\" restart_archon_run",
            "      status=$?",
            "      if [ \"$status\" -eq 0 ]; then",
            `      report_ao_status working "$(report_archon_note ${shellEscape(resumeRestartNote)})" || true`,
            "        run_dark_factory_stage \"archon workflow wait\" wait_archon_run",
            "        status=$?",
            "      fi",
            "    fi",
            "  else",
            "    dark_factory_archon_run_id=\"$(DARK_FACTORY_ARCHON_ALLOW_FAILED_DISCOVERY=1 discover_archon_run_id || true)\"",
            "    if [ -n \"$dark_factory_archon_run_id\" ]; then",
            "      export DARK_FACTORY_ARCHON_RUN_ID=\"$dark_factory_archon_run_id\"",
            "      dark_factory_archon_run_active=1",
            `    report_ao_status working "$(report_archon_note ${shellEscape(resumeFallbackNote)})" || true`,
            "      if archon_run_resumable; then",
            "        run_dark_factory_stage \"archon workflow resume\" resume_archon_run",
            "        status=$?",
            "        if [ \"$status\" -eq 0 ]; then",
            "          run_dark_factory_stage \"archon workflow wait\" wait_archon_run",
            "          status=$?",
            "        fi",
            "      elif [ \"$archon_resumable_status\" = \"running\" ] || [ \"$archon_resumable_status\" = \"pending\" ]; then",
            "        run_dark_factory_stage \"archon workflow wait\" wait_archon_run",
            "        status=$?",
            "      else",
            "        status=1",
            "      fi",
            "      if [ \"$status\" -ne 0 ]; then",
            "        run_dark_factory_stage \"archon workflow restart\" restart_archon_run",
            "        status=$?",
            "        if [ \"$status\" -eq 0 ]; then",
            `        report_ao_status working "$(report_archon_note ${shellEscape(resumeRestartNote)})" || true`,
            "          run_dark_factory_stage \"archon workflow wait\" wait_archon_run",
            "          status=$?",
            "        fi",
            "      fi",
            "    else",
            "      run_dark_factory_stage \"archon workflow start\" start_archon_run",
            "      status=$?",
            "      if [ \"$status\" -eq 0 ]; then",
            `      report_ao_status working "$(report_archon_note ${shellEscape(resumeFallbackNote)})" || true`,
            "        run_dark_factory_stage \"archon workflow wait\" wait_archon_run",
            "        status=$?",
            "      fi",
            "    fi",
            "  fi",
            "fi",
          ] : [
            "run_dark_factory_stage \"archon workflow start\" start_archon_run",
            "status=$?",
            "if [ \"$status\" -eq 0 ]; then",
            `  report_ao_status working "$(report_archon_note ${shellEscape(acknowledgeNote)})" || true`,
            "  run_dark_factory_stage \"archon workflow wait\" wait_archon_run",
            "  status=$?",
            "fi",
          ]),
          "if [ \"$status\" -ne 0 ]; then",
          `  report_ao_status failed "$(report_archon_note ${shellEscape(failedNote)})" || true`,
          "  exit \"$status\"",
          "fi",
          ...(isResume ? [
            "if [ \"$dark_factory_restore_direct_prepare\" != \"1\" ]; then",
            `  run_dark_factory_stage "report auto-feature completed" report_ao_status working "$(report_archon_note ${shellEscape(completedNote)})" || true`,
            `  run_dark_factory_stage "report pr opened" report_ao_pr_status pr-created "$(report_archon_note ${shellEscape(prOpenedNote)})" || true`,
            "fi",
          ] : [
            `run_dark_factory_stage "report auto-feature completed" report_ao_status working "$(report_archon_note ${shellEscape(completedNote)})" || true`,
            `run_dark_factory_stage "report pr opened" report_ao_pr_status pr-created "$(report_archon_note ${shellEscape(prOpenedNote)})" || true`,
          ]),
          `run_dark_factory_stage "report auto-merge preparing" report_ao_status working "$(report_archon_note ${shellEscape(mergeNote)})" || true`,
          "run_dark_factory_stage \"auto-merge prepare\" node \"${AGENTS_SKILLS_DIR:-$HOME/.agents/skills}/auto-merge/scripts/auto-merge.mjs\" --mode prepare",
          "status=$?",
          "if [ \"$status\" -eq 0 ]; then",
          "  if run_dark_factory_stage \"ready artifact\" write_dark_factory_ready; then",
          `    report_ao_pr_status ready-for-review "$(report_archon_note ${shellEscape(readyNote)})"`,
          "  else",
          "    status=1",
          `    report_ao_status failed "$(report_archon_note ${shellEscape(mergeFailedNote)})" || true`,
          "  fi",
          "else",
          `  report_ao_status failed "$(report_archon_note ${shellEscape(mergeFailedNote)})" || true`,
          "fi",
          "exit \"$status\"",
        ].join("\n");
      },

      getRestoreCommand(session, projectConfig) {
        return this.getLaunchCommand({
          sessionId: session?.id,
          issueId: session?.issueId ?? session?.issue,
          prompt: session?.prompt,
          projectConfig,
          restore: true,
        });
      },

      getEnvironment(config) {
        const agentConfig = config.projectConfig?.agentConfig ?? {};
        const projectId = String(agentConfig.darkFactoryProjectId ?? "").trim();
        const sessionId = String(config.sessionId ?? "").trim();
        const issueId = String(config.issueId ?? "").trim();
        const ports = sessionPortPair(sessionId);

        return {
          AO_SESSION_ID: sessionId,
          ...(issueId ? { AO_ISSUE_ID: issueId } : {}),
          ...(projectId ? { DARK_FACTORY_PROJECT_ID: projectId } : {}),
          ...(sessionId ? { DARK_FACTORY_SESSION_ID: sessionId } : {}),
          ...(issueId ? { DARK_FACTORY_ISSUE_ID: issueId } : {}),
          ...(projectId && sessionId ? { COMPOSE_PROJECT_NAME: composeProjectName(projectId, sessionId) } : {}),
          CHROME_PROFILE_MODE: "temp",
          ...(sessionId ? {
            PORT: ports.apiPort,
            WEB_PORT: ports.webPort,
            ...resolveRuntimeEnv(agentConfig, ports, { projectId, sessionId, issueId }),
            DARK_FACTORY_API_PORT: ports.apiPort,
            DARK_FACTORY_WEB_PORT: ports.webPort,
          } : {}),
        };
      },

      detectActivity(terminalOutput) {
        if (/workflow.*completed|completed successfully|process exited/i.test(terminalOutput)) {
          return "idle";
        }
        if (/error|failed|exception/i.test(terminalOutput)) {
          return "blocked";
        }
        return terminalOutput.trim() ? "active" : "idle";
      },

      async getActivityState(session) {
        const running = await this.isProcessRunning(session.runtimeHandle);
        if (running === true) return { state: "active", timestamp: new Date() };
        if (running === false) return { state: "exited", timestamp: new Date() };
        return null;
      },

      async isProcessRunning(handle) {
        const pid = getPid(handle);
        if (!pid) return "indeterminate";
        return isPidRunning(pid);
      },

      async getSessionInfo(session) {
        return {
          summary: session.issueId ? `Archon workflow for ${session.issueId}` : "Archon workflow",
          agentSessionId: null,
        };
      },
    };
  },
};

export default plugin;
